### ISSUE TITLE
   Can't open file: install\include\constant.php

### ISSUE THREAD

**Issue by josefnpat** [advocaite/Travianx#3]
System:

<pre>
PHP 5.3.5-1ubuntu7.2 with Suhosin-Patch (cli) (built: May  2 2011 23:00:17) 
Copyright (c) 1997-2009 The PHP Group
Zend Engine v2.3.0, Copyright (c) 1998-2010 Zend Technologies
mysql  Ver 14.14 Distrib 5.1.54, for debian-linux-gnu (x86_64) using readline 6.2
</pre>

Seems that with I submit the data from http://localhost/seppi/Travianx/install/?s=1, i encounter the following issue:

<pre>
Can't open file: install\include\constant.php
</pre>

I am especially concerned because the slashes are backwards.

**Comment by kasra-st** [comment]
I have same problem and There is no Constant.php in install/include directory
